FROM ruby:2.3
RUN  gem install --quiet --no-document fpm

ARG binary_name
ARG deb_package_name
ARG version
ARG version_string
ARG deb_package_description
ARG pkg_vendor
ARG pkg_maintainer
ARG pkg_url

RUN mkdir -p /deb-package/usr/bin /deb-package/var/log/prometheus \
  && wget https://github.com/prometheus/blackbox_exporter/releases/download/v$version/blackbox_exporter-$version.linux-amd64.tar.gz \
  && tar xfz blackbox_exporter-$version.linux-amd64.tar.gz \
  && cp blackbox_exporter-$version.linux-amd64/blackbox_exporter /deb-package/usr/bin/$binary_name
COPY dpkg-sources/dirs /deb-package
RUN mkdir dpkg-sources
COPY dpkg-sources /dpkg-sources
WORKDIR dpkg-sources
RUN fpm --output-type deb \
  --input-type dir --chdir /deb-package \
  --name $binary_name \
  --version $version_string \
  --description "${deb_package_description}" \
  --vendor "${pkg_vendor}" \
  --maintainer "${pkg_maintainer}" \
  --url "${pkg_url}" \
  --deb-init "startup/prometheus-blackbox-exporter" \
  --deb-default "prometheus-blackbox-exporter" \
  -p ${deb_package_name}-${version_string}.deb \
  etc usr && cp *.deb /deb-package/
